export const CONTEXT_JWT = {
  CREATE: '[CREATE TOKEN]',
  CREATE_ACCESS_SECRET: '[CREATE JWT_ACCESS_SECRET]',
  CREATE_REFRESH_SECRET: '[CREATE JWT_REFRESH_SECRET]',
  VALIDATE: '[VALIDATE TOKEN]',
} as const;
