export const CONTEXT_AUTH = {
  LOGIN: '[LOGIN USER]',
  CREATE_TOKEN: '[CREATE TOKEN USER]',
  REFRESH_TOKEN: '[REFRESH TOKEN USER]',
  REGISTER: '[REGISTER USER]',
  FORGOT_PASSWORD: '[FORGOT PASSWORD USER]',
  RESET_PASSWORD: '[RESET PASSWORD USER]',
  LOGOUT: '[LOGOUT USER]',
} as const;