export const CONTEXT_AUTH = {
  LOGIN: '[LOGIN AUTH]',
  REGISTER: '[REGISTER AUTH]',
  FORGOT_PASSWORD: '[FORGOT PASSWORD AUTH]',
  RESET_PASSWORD: '[RESET PASSWORD AUTH]',
  VALIDATE_TOKEN: '[VALIDATE TOKEN AUTH]',
} as const;
